# Generated by Django 4.2.6 on 2023-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('catogary', models.CharField(max_length=20)),
                ('published_date', models.DateField(null=True)),
                ('pages', models.PositiveIntegerField(null=True)),
                ('cover_image', models.ImageField(null=True, upload_to='')),
                ('rating', models.CharField(choices=[('1', '*'), ('2', '*'), ('3', '*'), ('4', '*'), ('5', '*')], max_length=5)),
            ],
        ),
    ]
