# Generated by Django 4.2.6 on 2023-11-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_books_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
